# Generated by Django 4.2.1 on 2023-06-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_address1_address_street1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(default=213456789, max_length=10),
            preserve_default=False,
        ),
    ]
