# Generated by Django 4.2.1 on 2023-06-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_alter_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
    ]
