# Generated by Django 4.2.1 on 2023-06-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_telephone_alter_user_username'),
        ('supermarket', '0007_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
